name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Instala as dependências do pyproject.toml
      
      - name: Run pylint and check score
        id: pylint
        run: |
          # Rodando pylint e extraindo a nota
          pylint --output-format=text $(git ls-files '*.py') > pylint_output.txt
          
          # Contando a média das notas
          score=$(grep -oP "Your code has been rated at \K[0-9]+\.[0-9]+" pylint_output.txt | awk '{s+=$1} END {print s/NR}')
          
          # Mostrando o resultado
          echo "Pylint score: $score"
          
          # Falhando se a pontuação for menor que 9
          if (( $(echo "$score < 9" | bc -l) )); then
            echo "Pylint score is below 9, failing the job."
            exit 1
          fi
          
      - name: Analysing the code with pylint (Optional detailed output)
        run: |
          cat pylint_output.txt  # Exibe a saída detalhada do Pylint (opcional)
