name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Instala as dependências do pyproject.toml
      
      - name: Run pylint and check score
        id: pylint
        run: |
          pylint --output-format=text $(git ls-files '*.py') > pylint_output.txt
          
          # Verificando se a pontuação foi gerada corretamente
          score=$(grep -o "Your code has been rated at [0-9]*\.[0-9]*" pylint_output.txt | awk '{print $7}')
          
          echo "Pylint score: $score"
          
          if [ -z "$score" ]; then
            echo "Error: Could not retrieve pylint score"
            exit 1
          fi

          if (( $(echo "$score < 8" | bc -l) )); then
            echo "Pylint score is below 8, failing the job."
            exit 1
          fi
          
      - name: Analysing the code with pylint (Optional detailed output)
        run: |
          cat pylint_output.txt  # Exibe a saída detalhada do Pylint (opcional)
